name: CI
on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: crystallang/crystal:1.0.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Crystal Ameba Linter
        uses: crystal-ameba/github-action@v0.2.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  spec:
    name: Spec
    runs-on: ubuntu-20.04

    steps:
      - name: Install rabbitmq
        run: sudo apt-get update && sudo apt-get install -y rabbitmq-server

      - name: Install Crystal
        run: |
          wget https://crystal-lang.org/install.sh
          chmod +x install.sh
          sudo ./install.sh --crystal=1.0.0

      - name: Checkout
        uses: actions/checkout@v2

      - name: Shards install
        run: shards install --ignore-crystal-version

      - name: Spec
        run: crystal spec --no-color --order random
