name: CI
on: [push]

jobs:
  lint:
    name: Spec
    runs-on: ubuntu-20.04
    container: crystallang/crystal:1.0.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Shards install
        run: shards install --ignore-crystal-version

      - name: Spec
        run: crystal spec --no-color --order random

      - name: Crystal Ameba Linter
        uses: crystal-ameba/github-action@v0.2.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
