name: CI
on: [push]

jobs:
  spec:
    name: Spec
    runs-on: ubuntu-latest
    container: 84codes/crystal:1.2.0-alpine-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Shards install
        run: shards install

      - name: Spec
        run: crystal spec --no-color --order random

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Crystal Ameba Linter
        uses: crystal-ameba/github-action@v0.2.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
