name: CI
on: [push]

jobs:
  spec:
    name: Spec
    runs-on: ubuntu-latest
    container: 84codes/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - run: shards install --production
      - name: Spec
        run: crystal spec --no-color --order random
  format:
    name: Formatting
    runs-on: ubuntu-latest
    container: 84codes/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Format check
        run: crystal tool format --check
  lint:
    name: Lint/Ameba
    runs-on: ubuntu-latest
    container: 84codes/crystal:latest-alpine
    steps:
      - name: Install deps
        run: apk add --no-cache make yaml-dev
      - uses: actions/checkout@v3
      - run: shards install
      - name: ameba
        run: bin/ameba --no-color
  docker:
    name: Docker container
    needs: [spec, format, lint]
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: 84codes/sparoid
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push container
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          tags: |
            84codes/sparoid:latest-alpine
            84codes/sparoid:latest
            84codes/sparoid:${{ env.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deb:
    name: Deb package
    needs: [spec, format, lint, docker]
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        name: Build deb
        with:
          platforms: linux/amd64,linux/arm64
          target: deb
          outputs: output
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Upload to PackageCloud any/any
        run: find output -name "*.deb" -exec curl -fsSu "${{ secrets.packagecloud_token }}:" -F "package[distro_version_id]=35" -F "package[package_file]=@{}" -XPOST https://packagecloud.io/api/v1/repos/cloudamqp/sparoid/packages.json \;
      - name: Upload to PackageCloud ubuntu/bionic
        run: find output -name "*.deb" -exec curl -fsSu "${{ secrets.packagecloud_token }}:" -F "package[distro_version_id]=190" -F "package[package_file]=@{}" -XPOST https://packagecloud.io/api/v1/repos/cloudamqp/sparoid/packages.json \;
      - name: Upload to PackageCloud ubuntu/focal
        run: find output -name "*.deb" -exec curl -fsSu "${{ secrets.packagecloud_token }}:" -F "package[distro_version_id]=210" -F "package[package_file]=@{}" -XPOST https://packagecloud.io/api/v1/repos/cloudamqp/sparoid/packages.json \;
      - name: Upload to PackageCloud debian/buster
        run: find output -name "*.deb" -exec curl -fsSu "${{ secrets.packagecloud_token }}:" -F "package[distro_version_id]=150" -F "package[package_file]=@{}" -XPOST https://packagecloud.io/api/v1/repos/cloudamqp/sparoid/packages.json \;
      - name: Upload to PackageCloud debian/bullseye
        run: find output -name "*.deb" -exec curl -fsSu "${{ secrets.packagecloud_token }}:" -F "package[distro_version_id]=207" -F "package[package_file]=@{}" -XPOST https://packagecloud.io/api/v1/repos/cloudamqp/sparoid/packages.json \;

  rpm:
    name: RPM package
    needs: [spec, format, lint]
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        os: [fedora-35]
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        run: echo "PKG_VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          file: Dockerfile.rpm
          platforms: linux/${{ matrix.arch }}
          build-args: |
            build_image=84codes/crystal:1.4.1-${{ matrix.os }}
            pkg_version=${{ env.PKG_VERSION }}
          outputs: builds
      - name: Upload to PackageCloud
        run: |
          set -eux
          curl -fsSO -u "${{ secrets.packagecloud_token }}:" https://packagecloud.io/api/v1/distributions.json
          ID=$(echo ${{ matrix.os }} | cut -d- -f1)
          VR=$(echo ${{ matrix.os }} | cut -d- -f2)
          DIST_ID=$(jq ".rpm[] | select(.index_name == \"${ID}\").versions[] | select(.index_name == \"${VR}\").id" distributions.json)
          find builds -name "*.rpm" | xargs -i \
            curl -fsS -u "${{ secrets.packagecloud_token }}:" -XPOST \
                 -F "package[distro_version_id]=${DIST_ID}" \
                 -F "package[package_file]=@{}" \
                 https://packagecloud.io/api/v1/repos/cloudamqp/sparoid/packages.json
