name: RPM packages
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_deb:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        os: [fedora-34]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version
        run: echo "PKG_VERSION=$(git describe --tags | cut -c2-)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build package
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.rpm
          platforms: linux/${{ matrix.arch }}
          build-args: |
            build_image=84codes/crystal:1.2.0-${{ matrix.os }}
            pkg_version=${{ env.PKG_VERSION }}
          outputs: builds

      - name: Upload to PackageCloud
        run: |
          set -eux
          curl -fsSO -u "${{ secrets.packagecloud_token }}:" https://packagecloud.io/api/v1/distributions.json
          ID=$(echo ${{ matrix.os }} | cut -d- -f1)
          VR=$(echo ${{ matrix.os }} | cut -d- -f2)
          DIST_ID=$(jq ".rpm[] | select(.index_name == \"${ID}\").versions[] | select(.index_name == \"${VR}\").id" distributions.json)
          find builds -name "*.rpm" | xargs -i \
            curl -fsS -u "${{ secrets.packagecloud_token }}:" -XPOST \
                 -F "package[distro_version_id]=${DIST_ID}" \
                 -F "package[package_file]=@{}" \
                 https://packagecloud.io/api/v1/repos/cloudamqp/sparoid/packages.json
